# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import tensorflow.keras



class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        self.MyMainWindow = MainWindow
        self.MyMainWindow.setObjectName("MainWindow")
        self.MyMainWindow.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self.MyMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # self.centralwidget.setWindowIcon(QtGui.QIcon('../images/app_icon1.png'))
        self.MyMainWindow.setWindowIcon(QtGui.QIcon('images/app_icon1.png'))
        self.backgroungImage = QtWidgets.QLabel(self.centralwidget)
        self.backgroungImage.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.backgroungImage.setAutoFillBackground(False)
        self.backgroungImage.setText("")
        self.backgroungImage.setPixmap(QtGui.QPixmap("images/background.png"))
        self.backgroungImage.setScaledContents(True)
        self.backgroungImage.setAlignment(QtCore.Qt.AlignCenter)
        self.backgroungImage.setObjectName("backgroungImage")
        self.backgroungImage.raise_()
        self.logoImage = QtWidgets.QLabel(self.centralwidget)
        self.logoImage.setGeometry(QtCore.QRect(0, 0, 80, 80))
        self.logoImage.setAutoFillBackground(False)
        self.logoImage.setText("")
        self.logoImage.setPixmap(QtGui.QPixmap("images/appLogo.png"))
        self.logoImage.setScaledContents(True)
        self.logoImage.setAlignment(QtCore.Qt.AlignCenter)
        self.logoImage.setObjectName("logoImage")
        self.newModelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.newModelBtn.setGeometry(QtCore.QRect(80, 280, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.newModelBtn.setFont(font)
        self.newModelBtn.setObjectName("newModelBtn")
        self.classifyEventBtn = QtWidgets.QPushButton(self.centralwidget)
        self.classifyEventBtn.setGeometry(QtCore.QRect(80, 210, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.classifyEventBtn.setFont(font)
        self.classifyEventBtn.setObjectName("classifyEventBtn")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(40, 520, 93, 28))
        self.exitBtn.setObjectName("exitBtn")
        self.prevResultsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.prevResultsBtn.setGeometry(QtCore.QRect(80, 350, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.prevResultsBtn.setFont(font)
        self.prevResultsBtn.setObjectName("prevResultsBtn")
        self.headLabel = QtWidgets.QLabel(self.centralwidget)
        self.headLabel.setGeometry(QtCore.QRect(80, 10, 521, 120))
        font = QtGui.QFont()
        font.setFamily("Elena")
        font.setPointSize(29)
        font.setBold(False)
        font.setWeight(75)
        self.headLabel.setFont(font)
        self.headLabel.setObjectName("headLabel")
        self.MyMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self.MyMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.MyMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self.MyMainWindow)
        self.statusbar.setObjectName("statusbar")
        self.MyMainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(self.MyMainWindow)
        QtCore.QMetaObject.connectSlotsByName(self.MyMainWindow)
        self.MyMainWindow.setStyleSheet(open('UI/style.css').read())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rumor Detection"))
        self.newModelBtn.setText(_translate("MainWindow", "Create New Model"))
        self.classifyEventBtn.setText(_translate("MainWindow", "Classify New Event"))
        self.exitBtn.setText(_translate("MainWindow", "Exit"))
        self.prevResultsBtn.setText(_translate("MainWindow", "View Previous Results"))
        self.headLabel.setText(_translate("MainWindow", "Twitter\nRumor\nDetection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
