# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewPreviousEvents.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ViewPreviousEvent(object):

    def setupUi(self, MainWindow):
        self.MainWin = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroungImage = QtWidgets.QLabel(self.centralwidget)
        self.backgroungImage.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.backgroungImage.setAutoFillBackground(False)
        self.backgroungImage.setText("")
        self.backgroungImage.setPixmap(QtGui.QPixmap("images/background.png"))
        self.backgroungImage.setScaledContents(True)
        self.backgroungImage.setAlignment(QtCore.Qt.AlignCenter)
        self.backgroungImage.setObjectName("backgroungImage")
        self.backgroungImage.raise_()
        self.logoImage = QtWidgets.QLabel(self.centralwidget)
        self.logoImage.setGeometry(QtCore.QRect(60, 0, 80, 80))
        self.logoImage.setAutoFillBackground(False)
        self.logoImage.setText("")
        self.logoImage.setPixmap(QtGui.QPixmap("images/appLogo.png"))
        self.logoImage.setScaledContents(True)
        self.logoImage.setAlignment(QtCore.Qt.AlignCenter)
        self.logoImage.setObjectName("logoImage")
        self.MainWin.setWindowIcon(QtGui.QIcon('images/app_icon1.png'))
        self.tableView = QtWidgets.QTableWidget(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(130, 80, 551, 431))
        self.tableView.setObjectName("tableView")
        self.tableView.setAlternatingRowColors(True)
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(30, 517, 101, 31))
        self.backBtn.setObjectName("backBtn")
        self.headLabel = QtWidgets.QLabel(self.centralwidget)
        self.headLabel.setGeometry(QtCore.QRect(140, 0, 700, 60))
        font = QtGui.QFont()
        font.setFamily("Elena")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(75)
        self.headLabel.setFont(font)
        self.headLabel.setObjectName("headLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.MainWin.setStyleSheet(open('UI/style.css').read())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Previous Events"))
        self.backBtn.setText(_translate("MainWindow", "< Back"))
        self.headLabel.setText(_translate("MainWindow", "Previously Classified Events"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ViewPreviousEvent()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
